<?php

/**
 * @file
 * A custom module provided by Real Tidings, LLC to tie some features together in the background.
 * for more sample code and starting points, visit http://drupal.org/project/examples
 */
 
/**
 * Wrapper for the dpm() function to prevent it from accidentally breaking your site if the devel module is inactive
 * note: we break the naming convention here for ease of use implementing this function
 */
function mydpm($input) {
  if (function_exists('dpm')) { 
      dpm($input);
  } else {
      echo '<pre>' . print_r($input, true) . '</pre>';
  }
}

/**
* Implements hook_page_alter(). 
*/
function rt_page_alter(&$page) {
	global $theme_key;
	if (variable_get('admin_theme') == $theme_key) {
		$page['content']['rt-footer'] = array(
			'#markup' => '<div id="rt-footer-admin"><h3>Need help?</h3><ul><li>please <a href="http://realtidings.com/support">submit a support request</a></li><li> or email <a href="mailto://support@realtidings.com">support@realtidings.com.</a></li></ul></div>', 
			'#weight' => 90,
		);
	} else {
		$page['page_bottom']['rt-footer'] = array(
			'#markup' => '<div id="rt-footer"><h2><a href="http://realtidings.com">Custom Drupal Website</a> by RealTidings, LLC</h2></div>', 
			'#weight' => 90,
		);
	}
}


/**
 * Site glue module by RealTidings
 * contact Ron if you need changes or have questions
 * admin@realtidings.com
 */